default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: lcsmachado
  password: 123456
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ruptiva_development
test:
  <<: *default
  database: ruptiva_test
production:
  <<: *default
  database: ruptiva_production
  username: ruptiva
  password: <%= ENV['RUPTIVA_DATABASE_PASSWORD'] %>
